### ISSUE TITLE
Обработка превышения запроса

### ISSUE THREAD

**Issue by artfaal** [artfaal/WisdomWave#2]
Добработка ошибки:
```
conn.close()
error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-ez2CcJQd6voRK0B9LxChI1q2 on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=tokens message='OpenAI API error received' stream_error=False
Task exception was never retrieved
future: <Task finished name='Task-7900' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=InvalidRequestError(message="This model's maximum context length is 8192 tokens. However, your messages resulted in 9197 tokens. Please reduce the length of the messages.", param='messages', code='context_length_exceeded', http_status=400, request_id=None)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/app/main.py", line 84, in handle_text_messages
    await ask_openai(message, message.text, "private", group_title)
  File "/app/main.py", line 107, in ask_openai
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 8192 tokens. However, your messages resulted in 9197 tokens. Please reduce the length of the messages.
```

**Comment by artfaal** [comment]
Добавлена обработка ошибок от openai
